---
title: "Worksheet#5a"
author: "Espadon, Gerona, Bernasol"
date: "2024-11-23"
output: pdf_document
---


```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r}
# Load necessary libraries
library(rvest)
library(httr)
library(dplyr)
library(polite)
```


```{r}
# Define target URL
url <- 'https://www.imdb.com/chart/toptv/'

# Create a polite session
session <- bow(url, user_agent = "Educational")

session
```


```{r}
#Extracting the ranks and titles
title_list <- read_html(url) %>%
html_nodes('.ipc-title__text') %>%
html_text()

title_list
```

```{r}
#Cleaning extracted text
title_list_sub <- as.data.frame(title_list[3:27], stringsAsFactors = FALSE)
colnames(title_list_sub) <- "ranks"

split_df <- strsplit(as.character(title_list_sub$ranks), "\\.", fixed = FALSE)
split_df <- data.frame(do.call(rbind, split_df), stringsAsFactors = FALSE)

colnames(split_df) <- c("rank", "title")
split_df <- split_df %>%
select(rank, title)

split_df$title <- trimws(split_df$title)

rank_title <- split_df
rank_title
```


```{r}
# Scrape Ratings
#Extracting tv rating, the number of people who voted, the number of episodes, and the year it was released.
rating_ls <- read_html(url) %>%
html_nodes('.ipc-rating-star--rating') %>%
html_text()

rating_ls
```


```{r}
# Scrape Vote Counts
voter_ls <- read_html(url) %>%
html_nodes('.ipc-rating-star--voteCount') %>%
html_text()

clean_votes <- gsub('[()]', '', voter_ls)
# Check if vote counts were extracted correctly
print(voter_ls)
```


```{r}
#extracted the number of episodes
eps_ls <- read_html(url) %>%
html_nodes('span.sc-300a8231-7.eaXxft.cli-title-metadata-item:nth-of-type(2)') %>%
html_text()
clean_eps <- gsub('[eps]', '', eps_ls)

num_eps <- as.numeric(clean_eps)

print(num_eps)
#note to self, use gsub() to remove constant strings appearing in the dataset.
```


```{r}
#extracted the year released
years <- read_html(url) %>%
html_nodes('span.sc-300a8231-7.eaXxft.cli-title-metadata-item:nth-of-type(1)') %>%
html_text()

years
```


```{r}
top_tv_shows <- data.frame(
Title = rank_title[,2],
Rating = rating_ls,
Voters = clean_votes,
Episodes = num_eps,
Year = years)


top_tv_shows
```



```{r}
home_link <- 'https://www.imdb.com/chart/toptv/'
main_page <- read_html(home_link)
```


```{r}
links <- main_page %>%
html_nodes("a.ipc-title-link-wrapper") %>%
html_attr("href")

links
```


```{r}
# Loop to get link of each show's page
show_data <- lapply(links, function(link) {
complete_link <- paste0("https://imdb.com", link)

#loop to get the link for user review page
usrv_link <- read_html(complete_link)
usrv_link_page <- usrv_link %>%
html_nodes('a.isReview') %>%
html_attr("href")

#loop to extract critic reviews
critic <- usrv_link %>%
html_nodes("span.score") %>%
html_text()
critic_df <- data.frame(Critic_Reviews = critic[2], stringsAsFactors = FALSE)

#loop to extract pop rating
pop_rating <- usrv_link %>%
html_nodes('[data-testid="hero-rating-bar__popularity__score"]') %>%
html_text()

#loop to get user reviews of each shows
usrv <- read_html(paste0("https://imdb.com", usrv_link_page[1]))
usrv_count <- usrv %>%
html_nodes('[data-testid="tturv-total-reviews"]') %>%
html_text()

return(data.frame(Show_Link = complete_link, User_Reviews = usrv_count, Critic = critic_df, Popularity_Rating = pop_rating))
})
```



```{r}
show_url_df <- do.call(rbind, show_data)
print(show_url_df)

shows <- cbind(top_tv_shows, show_url_df)
shows
```


```{r}
#knitr::kable()

library(kableExtra)

knitr::kable(shows,caption = "Extracting Rating, VoteCount, Episodes, Year and Reviews") %>%
kable_classic(full_width = T, html_font = "Cambria") %>%
kable_styling(font_size = 8)
```


```{r}
library(kableExtra)

movies <- shows[c(1:5),]

knitr::kable(movies, caption = "IMDB Movies") %>%
kable_classic(full_width = T, html_font = "Arial Narrow") %>%
kable_styling(font_size = 8)
```


